---
- name: Install OpenSC
  yum: 
    name: opensc
    state: present

- name: Create easy-rsa folder
  file:
    path: /etc/openvpn/easy-rsa
    recurse: yes
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Copy easy-rsa files
  shell: cp -rf /usr/share/easy-rsa/2.0/* /etc/openvpn/easy-rsa
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Copy CA vars to the server
  copy:
    src: files/vars
    dest: /etc/openvpn/easy-rsa/vars
    force: yes
    owner: root
    group: root
    mode: 0755

- name: Copy OpenSSL conf file
  shell: cp /etc/openvpn/easy-rsa/openssl-1.0.0.cnf /etc/openvpn/easy-rsa/openssl.cnf    
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Source vars
  shell: source ./vars
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Clean up any old keys
  shell: ./clean-all
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build CA
  shell: ./build-ca
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Generate server key
  shell: ./build-key-server server
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Create Diffie-Helmann file
  shell: ./build-dh
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Copy all keys to OpenVPN directiry
  shell: cp dh2048.pem ca.crt server.crt server.key /etc/openvpn
  args:
    chdir: /etc/openvpn/easy-rsa/keys

