---
- name: Create directory for configs
  file:
    path: /etc/openvpn
    mode: 0755
    owner: root
    group: root
    state: directory

- name: Copy config file to the server
  copy:
    src: files/server.conf
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644