---
- name: Upload script
  file:
    src: keygenerate.py
    dest: /var/www/cgi-bin/keygenerate.py
    owner: apache
    group: apache
    mode: 0544

 - name: Upload script
   file:
    src: keygenerate.py
    dest: /var/www/cgi-bin/keygenerate.py
    owner: apache
    group: apache
    mode: 0644
