---
- name: Upgrade all packages
  yum: name=* state=latest

- name: Install EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Install openvpn
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - openvpn
    - openssl
    - easy-rsa
    - opensc

