---
openvpn_server_ip: 192.168.1.41
openvpn_server_port: 1194
openvpn_port: 1194

# defaults file for openvpn
openvpn_base_dir: /etc/openvpn
client_name: client
ca_name: ca
openvpn_cert: "{{ openvpn_base_dir }}/{{ client_name }}.crt"
openvpn_key: "{{ openvpn_base_dir }}/{{ client_name }}.key"
openvpn_ca_cert: "{{ openvpn_base_dir }}/{{ ca_name }}.crt"
openvpn_log_dir: /var/log/openvpn
openvpn_server_hostname: "{{inventory_hostname}}"
openvpn_proto: udp
openvpn_dualstack: true
openvpn_rsa_bits: 2048
openvpn_service_name: openvpn


#Unused
openvpn_uninstall: false
openvpn_use_pregenerated_dh_params: false
openvpn_use_modern_tls: true
openvpn_verify_cn: false
openvpn_redirect_gateway: true
openvpn_set_dns: true
openvpn_enable_management: false

openvpn_management_bind: /var/run/openvpn/management unix
openvpn_management_client_user: root
openvpn_server_network: 10.8.0.0
openvpn_server_netmask: 255.255.255.0

tls_auth_required: true
ci_build: false
clients: []
openvpn_push: []
manage_firewall_rules: true
openvpn_client_register_dns: true
openvpn_use_crl: false
openvpn_duplicate_cn: false
openvpn_status_version: 1

